<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# ASSIGNMENT

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.

- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [1]:
##### Begin Working Here #####
# getting lending club data
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2019-09-05 22:36:29--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip’

LoanStats_2018Q4.cs     [                 <=>]  21.58M   845KB/s    in 26s

2019-09-05 22:36:55 (836 KB/s) - ‘LoanStats_2018Q4.csv.zip’ saved [22631049]

In [2]:
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
  inflating: LoanStats_2018Q4.csv

In [3]:
# shows the first set of data
!head LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","10000","10000","10000"," 36 months"," 10.33%","324.23","B","B1","","< 1 year","MORTGAGE","280000","Not Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","974xx","OR","6.15","2","Jan-1996","0","18","","14","0","9082","38%","23","w","8289.30","8289.30","2261.0","2261.00","1710.70","550.30","0.0","0.0","0.0","Jul-2019","324.23","Sep-2019","Aug-2019","0","","1","Individual","","","","0","671","246828","1","3","2","3","1","48552","62","1","3","4923","46","23900","2","7","1","7","17631","11897","43.1","0","0","158","275","11","1","1","11","","11","","0","3","4","7","7","10","9","11","4","14","0","0","0","4","91.3","28.6","0","0","367828","61364","20900","54912","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","4000","4000","4000"," 36 months"," 23.40%","155.68","E","E1","Security","3 years","RENT","90000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","070xx","NJ","26.33","0","Sep-2006","4","59","","15","0","5199","19.2%","20","w","3423.38","3423.38","1081.96","1081.96","576.62","505.34","0.0","0.0","0.0","Jul-2019","155.68","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","66926","5","4","3","4","5","61727","86","6","11","1353","68","27100","4","0","4","15","4462","20174","7.9","0","0","147","118","2","2","0","2","","0","","0","5","7","9","9","8","11","12","7","15","0","0","0","9","95","0","0","0","98655","66926","21900","71555","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 17.97%","180.69","D","D1","Administrative","6 years","MORTGAGE","59280","Source Verified","Dec-2018","Late (31-120 days)","n","","","debt_consolidation","Debt consolidation","490xx","MI","10.51","0","Apr-2011","0","","","8","0","4599","19.1%","13","w","4456.17","4456.17","895.96","895.96","543.83","352.13","0.0","0.0","0.0","Jun-2019","180.69","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","110299","0","1","0","2","14","7150","72","0","2","0","35","24100","1","5","0","4","18383","13800","0","0","0","87","92","15","14","2","77","","14","","0","0","3","3","3","4","6","7","3","8","0","0","0","0","100","0","0","0","136927","11749","13800","10000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 60 months"," 20.89%","620.81","D","D4","Operator","5 years","RENT","68107","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","672xx","KS","0.52","0","Feb-1997","0","","","5","0","976","13%","10","w","21353.16","21353.16","4307.45","4307.45","1646.84","2660.61","0.0","0.0","0.0","Jul-2019","620.81","Sep-2019","Aug-2019","1","","1","Individual","","","","0","2693","976","0","0","0","0","36","0","","3","4","0","13","7500","2","2","4","4","195","3300","0","0","0","237","262","10","10","0","10","","9","","0","0","1","3","4","3","5","7","1","5","0","0","0","3","100","0","0","0","7500","976","3300","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","8000","8000","8000"," 36 months"," 23.40%","311.35","E","E1","Manager","10+ years","OWN","43000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","357xx","AL","33.24","0","Jan-1995","0","","107","8","1","9019","81.3%","16","w","6846.83","6846.83","2163.85","2163.85","1153.17","1010.68","0.0","0.0","0.0","Jul-2019","311.35","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","169223","0","3","2","2","7","22059","69","0","0","2174","72","11100","1","1","1","2","21153","126","94.5","0","0","148","287","44","7","1","51","","7","","0","1","4","1","2","8","4","7","4","8","0","0","0","2","100","100","1","0","199744","31078","2300","32206","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","32075","32075","32075"," 60 months"," 11.80%","710.26","B","B4","Nursing Supervisor","10+ years","MORTGAGE","150000","Not Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","231xx","VA","22.21","0","Aug-2005","0","","","17","0","19077","32%","24","w","29228.12","29228.12","4940.28","4940.28","2846.88","2093.40","0.0","0.0","0.0","Jul-2019","710.26","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","272667","1","4","1","1","9","37558","47","1","1","3910","41","59600","1","2","0","3","16039","10446","47.8","0","0","160","70","4","4","2","27","","14","","0","4","10","4","4","8","12","14","10","17","0","0","0","2","100","50","0","0","360433","56635","20000","80125","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","9600","9600","9600"," 36 months"," 12.98%","323.37","B","B5","","n/a","MORTGAGE","35704","Not Verified","Dec-2018","Current","n","","","home_improvement","Home improvement","401xx","KY","0.84","0","Nov-2003","0","69","","5","0","748","11.5%","23","w","8012.51","8012.51","2287.83","2287.83","1587.49","700.34","0.0","0.0","0.0","Aug-2019","323.37","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","748","0","0","0","0","44","0","","0","3","748","12","6500","0","0","1","3","150","3452","17.8","0","0","181","100","13","13","0","16","","3","","0","1","1","2","2","16","5","7","1","5","0","0","0","0","95.5","0","0","0","6500","748","4200","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","30000","30000","30000"," 60 months"," 18.94%","777.23","D","D2","Postmaster ","10+ years","MORTGAGE","90000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","713xx","LA","26.52","0","Jun-1987","0","71","75","13","1","12315","24.2%","44","w","19969.40","19969.40","12893.26","12893.26","10030.60","2862.66","0.0","0.0","0.0","Jul-2019","777.23","Sep-2019","Aug-2019","0","","1","Individual","","","","0","1208","321915","4","4","2","3","3","87153","88","4","5","998","57","50800","2","15","2","10","24763","13761","8.3","0","0","163","378","4","3","3","4","","4","","0","2","4","4","9","27","8","14","4","13","0","0","0","6","95","0","1","0","372872","99468","15000","94072","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [4]:
# shows the end set of the data
!tail LoanStats_2018Q4.csv

"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","4264.17","4264.17","1891.55","1891.55","1335.83","555.72","0.0","0.0","0.0","Aug-2019","190.21","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","7655.00","7655.00","3459.26","3459.26","2345.00","1114.26","0.0","0.0","0.0","Aug-2019","346.76","Sep-2019","Aug-2019","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","3807.30","3807.30","1694.53","1694.53","1192.70","501.83","0.0","0.0","0.0","Aug-2019","169.83","Sep-2019","Aug-2019","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","7544.75","7356.13","3261.44","3179.90","2455.25","806.19","0.0","0.0","0.0","Aug-2019","327.68","Sep-2019","Aug-2019","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","7706.67","7706.67","3551.41","3551.41","2293.33","1258.08","0.0","0.0","0.0","Aug-2019","356.08","Sep-2019","Aug-2019","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2050909275
Total amount funded in policy code 2: 820109297

In [30]:
import pandas as pd

#df = pd.read_csv('LoanStats_2018Q4.csv')

# to remove the bold rendering of data header = 1

# df = pd.read_csv('LoanStats_2018Q4.csv',header = 1)

## na_values - Additional strings to recognize as NA/NaN
#df = pd.read_csv('LoanStats_2018Q4.csv',header = 1,na_values=['n/a'])

## to clean the data in the bottom use skip footer
df = pd.read_csv('LoanStats_2018Q4.csv',header = 1,na_values=['n/a'],skipfooter=2)


df.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  del sys.path[0]

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,10000,10000,10000.0,36 months,10.33%,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8289.30,8289.30,2261.00,2261.00,1710.70,550.30,0.0,0.0,0.0,Jul-2019,324.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,4000,4000,4000.0,36 months,23.40%,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3423.38,3423.38,1081.96,1081.96,576.62,505.34,0.0,0.0,0.0,Jul-2019,155.68,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97%,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (31-120 days),n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.96,895.96,543.83,352.13,0.0,0.0,0.0,Jun-2019,180.69,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,23000,23000,23000.0,60 months,20.89%,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21353.16,21353.16,4307.45,4307.45,1646.84,2660.61,0.0,0.0,0.0,Jul-2019,620.81,Sep-2019,Aug-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,8000,8000,8000.0,36 months,23.40%,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,6846.83,6846.83,2163.85,2163.85,1153.17,1010.68,0.0,0.0,0.0,Jul-2019,311.35,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# set display option to avoid truncation of rows and/or columns

pd.set_option('display.max_rows',500)
pd.set_option('display.max_columns',500)

df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,10000,10000,10000.0,36 months,10.33%,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8289.30,8289.30,2261.00,2261.00,1710.70,550.30,0.0,0.0,0.0,Jul-2019,324.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,4000,4000,4000.0,36 months,23.40%,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3423.38,3423.38,1081.96,1081.96,576.62,505.34,0.0,0.0,0.0,Jul-2019,155.68,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97%,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (31-120 days),n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.96,895.96,543.83,352.13,0.0,0.0,0.0,Jun-2019,180.69,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,23000,23000,23000.0,60 months,20.89%,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21353.16,21353.16,4307.45,4307.45,1646.84,2660.61,0.0,0.0,0.0,Jul-2019,620.81,Sep-2019,Aug-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,8000,8000,8000.0,36 months,23.40%,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,6846.83,6846.83,2163.85,2163.85,1153.17,1010.68,0.0,0.0,0.0,Jul-2019,311.35,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df['emp_title']

0                                              NaN
1                                         Security
2                                   Administrative
3                                         Operator
4                                          Manager
5                               Nursing Supervisor
6                                              NaN
7                                      Postmaster
8                                             Chef
9                                              NaN
10                                Material Handler
11                       Instructional Coordinator
12                Financial Relationship Associate
13                                             NaN
14                             Sale Representative
15                             driver coordinator
16                                   gas attendant
17                                      Processor
18                     Neonatal Nurse Practitioner
19                             Stationary Engineer
20                                             NaN
21                               Exhibits director
22                                Worship Director
23                                 Program Manager
24                                             NaN
25                 Budget & Procurement Specialist
26                                             NaN
27                                        Mechanic
28                                   IT Supervisor
29                                    Director COE
30                                 Account Manager
31                              Assistant Director
32                             Legal Assistant III
33                      Program Support Assistant
34                                             NaN
35                                Business Analyst
36                                             NaN
37                                 Program Manager
38                        VP, Solutions Management
39                                         Teacher
40                                             NaN
41                                          BANKER
42                           PRIVATE CLIENT BANKER
43                                        OPERATOR
44                                          Driver
45                             Service Consultant
46                                         Teacher
47                                             NaN
48                                   case manager
49                                Shift Supervisor
50                                           Sever
51                                  Vice President
52                                     Tech Driver
53                                         Teacher
54                              Operations Manager
55                                             NaN
56                            Supply Chain Analyst
57                                             NaN
58                                             NaN
59                       Product Line Specilalist
60                                  Medical Doctor
61                     Enrollment Services Advisor
62                                            Army
63                                  Room Attendant
64                              Compliance manager
65                                     Haz Mat S/R
66                Sr. Vice President -Risk Manager
67                                             NaN
68                                Shift Supervisor
69                                             NaN
70                               Workforce Analyst
71                                         Captain
72                                  Senior manager
73                          Reference/YA Librarian
74                        Manager, Patient Finance
75                                      bus driver
76                                  Bakery Manager
77                                    Esthetician
78                        Senior Software Engineer
79                             Software Consultant
80                               Financial Planner
81                 Senior Director Risk Management
82                                             NaN
83                               Software Engineer
84                                             NaN
85                                         Manager
86                                Vacation Advisor
87                                         Manager
88                            Operation s director
89                              Machinst/Programer
90                            Help Tech Supervisor
91                         Operations Coordinator
92             Corporate Communications Strategist
93                                 Project Manager
94                                         Analyst
95                                   Service tech.
96                                   Especialist 1
97                                        Shipping
98                                         Teacher
99                                   Receptionist
100                                        Teacher
101                                            NaN
102                                     Supervisor
103                           Extrusion assistant
104                         DISTRICT SALES MANAGER
105                                Staff Physician
106                                         Server
107                              Director of Sales
108                                     Controller
109                                            NaN
110                                          Sales
111                                   senior buyer
112                                        Manager
113                                     Consultant
114                                      President
115                               Nurse technician
116                            Maintenance Manager
117                                Math Instructor
118                                   Firefighter
119                      Senior Area Sales Manager
120                       Director of reinsurance
121                               Header operator
122                                        Banker
123                           Warehouse Associates
124                                        Teacher
125                        Paramedic/ Fire Fighter
126                                    Supervisor
127                           overnight supervisor
128                                        teacher
129                                Sr. CAE Analyst
130                                   Tire builder
131                                 Claims Analyst
132                         procurement supervisor
133                        radiologic technologist
134                               Training Manager
135                                            RN
136                      elementary school teacher
137                                     supervisor
138                                Sale Consultant
139                          Accounts Examiner III
140                                            NaN
141                                      Educator
142                                            NaN
143                                General Manager
144                                    Casino Host
145                                      Carpenter
146                           MAINTENANCE PLANNER
147       Assistant Athletic Director of Marketing
148                               Sr Sales Manager
149                                            NaN
150                                            NaN
151                            Firefighter/captain
152             Executive Administrative Assistant
153                                            NaN
154                                       Optician
155                                            NaN
156                                 Bill Collector
157                             Production Manager
158                                        Printer
159                                Program Manager
160                              Surgery scheduler
161                         Mail Processing Clerk
162                                     Conductor
163                                           LMSW
164                                       Attorney
165                                        Teacher
166                                            Lpn
167                                Project Manager
168                           Medical Technologist
169                           Construction Manager
170                      Administrative Assistant
171                         Transportation Manager
172                                     Pharmacist
173                            Structural Engineer
174                                   IT Assistant
175       Anti Money Laundering Compliance Manager
176                            Compliance Director
177                          Veterinary Assistant
178                                Project manager
179                               Regional Manager
180                           DIRECT CARE PROVIDER
181                                    Supervisor
182                                            NaN
183                                account manager
184                                            NaN
185                               General Manager
186                                  Medical Coder
187                        Plant Logistics Manager
188                                     Millwright
189                              Fuel truck driver
190                                   MAINTENANCE
191                                       Sales VP
192        Publications and Images Project Manager
193                                        Trainer
194                         Armed Security officer
195                                            NaN
196                                       Director
197                                        Manager
198                                          Agent
199                        Mortgage loan processor
200                                           CFO
201                                            NaN
202                                        Laborer
203                                         Driver
204           Lead Transportation Security Officer
205                                General Manager
206                                 Vice President
207                                        Dealer
208                                 OFFICE MANAGER
209                                      Goldsmith
210                                            Lpn
211                                       Teacher
212                                       lab tech
213                               customer service
214                                            NaN
215                                            NaN
216                      Facility Maintenance Tech
217                                        Plumber
218                                       asst.mgr
219                                 Police Captain
220                                            Cna
221                              Financial Advisor
222                                            NaN
223                                            NaN
224                                    City Crrier
225                                       Engineer
226                      Reimbursement specialist
227                                  Asst. Manager
228               Instructor for Training Squadron
229                                        Driver
230           Assistant to the Treasurer (Payroll)
231                                   UPS/Shipping
232                               Attorney-Adviser
233                                        Teacher
234                          Sales Account Manager
235                                            NaN
236                                 Office Manager
237                                            NaN
238                                     Consultant
239                         Quality Field Engineer
240                                        Teller
241                           respritory therapist
242                                            NaN
243                           Job Coach Supervisor
244                                  Foreman shop
245                      Substance Abuse Counselor
246                 Business Intelligence Engineer
247                                             FC
248                                            NaN
249                        Information technology
                            ...
128162                     Maintenance Supervisor
128163                                         NaN
128164                                         NaN
128165                          Payroll Specialist
128166                       Surgical Technologist
128167                     Service Center Manager
128168                                    Attorney
128169                Network Server Administrator
128170                                         NaN
128171                        Automotive  Mechanic
128172                                         NaN
128173                                         NaN
128174                          nurse practitioner
128175                                Bank Teller
128176                                     Manager
128177                       Computer Operator III
128178                                   maintence
128179                                         NaN
128180                                         NaN
128181                                         NaN
128182                                      Driver
128183                                         NaN
128184                                         NaN
128185                         Clerical Associate
128186                              Warehouse Lead
128187                                       Nurse
128188                           Quality Inspector
128189                               Lumber Grader
128190               Supervisor of administration
128191                                    Clerical
128192                    Assembly Line Technician
128193                                   Assembler
128194                                  Operations
128195                        FSC Sales Supervisor
128196                                City Carrier
128197          Supervisory Air Interdiction Agent
128198                             Project Manager
128199                 Senior Director Engineering
128200                        Childcare instructor
128201                              Physician Asst
128202                            Sales Consultant
128203                            Sales/Technician
128204                                         NaN
128205                                         NaN
128206                                         NaN
128207                                         NaN
128208                                         NaN
128209                                  Maint tech
128210                             General Manager
128211     Sr. Vice President Business Development
128212                                     Stocker
128213               Operational Risk  consultant
128214                           Systems Developer
128215                                         NaN
128216                                       Nurse
128217                     Human Resource Director
128218                                          RN
128219                                         NaN
128220                            IT Systems Spec.
128221              Major Hampton Sheriff's Office
128222                       Senior CAD Technician
128223                               Probate judge
128224                                    Bellman
128225                Certified medical assistant
128226                                         NaN
128227                      Operations specialist
128228                                     manager
128229                                         NaN
128230                                    Prepador
128231                                         NaN
128232        Service member- Sergeant First Class
128233                                         NaN
128234              Quality assurance coordinator
128235                              Superintendent
128236                               Plant manager
128237                              Hvac mechanic
128238                                         NaN
128239       Senior Client Service Representative
128240                                   Architect
128241                             General Clerk 2
128242                               Scientist III
128243                           Level 1 inspector
128244                    Advance Quality Engineer
128245        Vice President, Business Development
128246                   Network Security Engineer
128247                           BSA Investigator
128248                                         NaN
128249                                         NaN
128250                                   Professor
128251                                Maintenance
128252                                         NaN
128253                             General Manager
128254                                         NaN
128255                      SENIOR CENTER DIRECTOR
128256                               Administrator
128257                                        Chef
128258                              Office Manager
128259                                  Controller
128260                                         NaN
128261                                         NaN
128262              Sales Manager/Used Car Manager
128263                                  Specialist
128264                                         NaN
128265                              executive chef
128266                                         NaN
128267                   Financial Administration
128268                                  RSR DRIVER
128269                     Insurance under writer
128270          Senior Manager of Audio Production
128271                            Paint Technician
128272                                         NaN
128273                            Retail Associate
128274                         HR Business Partner
128275                                         NaN
128276                                  Data Clerk
128277                                  Paralegal
128278                          Campus supervisor
128279                                   AP Clerk
128280                                         NaN
128281                                         NaN
128282                              Home Caregiver
128283                         Casino table games
128284                                VP, of Sales
128285                                  Bookkeeper
128286                              Budget Manager
128287                                 Coordinator
128288                                         NaN
128289                                         NaN
128290                                         NaN
128291                              Client Partner
128292                     Materials Launch Manage
128293                                Line Manager
128294      Contractor (IT & Software Development)
128295                regional performance manager
128296                              Superintendant
128297          Medical Records Billing Specialist
128298                         Solutions Architect
128299                                     Teacher
128300                      Contact Representative
128301              Associate Director of Catering
128302                        Retail Store Manager
128303           Principal Application Architect I

In [9]:
# To get the no. of column headers of my dataset
# list shows them vertically
# len gives the length of it

len(list(df.columns))

144

In [10]:
# I can use the shape method to get the number of rows or columns
df.shape[1]

144

In [11]:
# look at the null values in the dataset
# isna() and isnull both works

#df.isnull().sum()

# to sort this - default is ascending

df.isnull().sum().sort_values(ascending=False)

id                                            128412
desc                                          128412
member_id                                     128412
url                                           128412
orig_projected_additional_accrued_interest    128386
hardship_type                                 128385
hardship_last_payment_amount                  128385
hardship_payoff_balance_amount                128385
hardship_reason                               128385
hardship_loan_status                          128385
hardship_dpd                                  128385
hardship_length                               128385
payment_plan_start_date                       128385
hardship_end_date                             128385
hardship_start_date                           128385
hardship_amount                               128385
deferral_term                                 128385
hardship_status                               128385
settlement_percentage                         128301
settlement_term                               128301
settlement_status                             128301
settlement_amount                             128301
settlement_date                               128301
debt_settlement_flag_date                     128301
sec_app_mths_since_last_major_derog           123258
verification_status_joint                     113564
mths_since_last_record                        112962
sec_app_revol_util                            111888
sec_app_open_act_il                           111630
sec_app_num_rev_accts                         111630
sec_app_chargeoff_within_12_mths              111630
sec_app_collections_12_mths_ex_med            111630
dti_joint                                     111630
annual_inc_joint                              111630
revol_bal_joint                               111630
sec_app_earliest_cr_line                      111630
sec_app_inq_last_6mths                        111630
sec_app_mort_acc                              111630
sec_app_open_acc                              111630
mths_since_recent_bc_dlq                      103243
mths_since_last_major_derog                    99232
mths_since_recent_revol_delinq                 91630
mths_since_last_delinq                         72196
emp_title                                      20947
il_util                                        20274
next_pymnt_d                                   16123
mths_since_recent_inq                          16047
emp_length                                     11704
mo_sin_old_il_acct                              4478
mths_since_rcnt_il                              4478
num_tl_120dpd_2m                                2859
bc_util                                         1754
percent_bc_gt_75                                1692
bc_open_to_buy                                  1691
mths_since_recent_bc                            1591
dti                                              237
last_pymnt_d                                     159
revol_util                                       156
all_util                                          37
avg_cur_bal                                       13
last_credit_pull_d                                 1
int_rate                                           0
initial_list_status                                0
out_prncp                                          0
out_prncp_inv                                      0
total_pymnt                                        0
total_pymnt_inv                                    0
total_rec_prncp                                    0
purpose                                            0
total_rec_int                                      0
total_acc                                          0
funded_amnt_inv                                    0
funded_amnt                                        0
total_rec_late_fee                                 0
recoveries                                         0
loan_amnt                                          0
collection_recovery_fee                            0
term                                               0
revol_bal                                          0
installment                                        0
pymnt_plan                                         0
loan_status                                        0
title                                              0
zip_code                                           0
addr_state                                         0
issue_d                                            0
delinq_2yrs                                        0
earliest_cr_line                                   0
verification_status                                0
annual_inc                                         0
inq_last_6mths                                     0
home_ownership                                     0
sub_grade                                          0
grade                                              0
open_acc                                           0
pub_rec                                            0
debt_settlement_flag                               0
open_il_12m                                        0
last_pymnt_amnt                                    0
num_sats                                           0
num_accts_ever_120_pd                              0
num_actv_bc_tl                                     0
num_actv_rev_tl                                    0
num_bc_sats                                        0
num_bc_tl                                          0
num_il_tl                                          0
num_op_rev_tl                                      0
num_rev_accts                                      0
num_rev_tl_bal_gt_0                                0
num_tl_30dpd                                       0
collections_12_mths_ex_med                         0
num_tl_90g_dpd_24m                                 0
num_tl_op_past_12m                                 0
pct_tl_nvr_dlq                                     0
pub_rec_bankruptcies                               0
tax_liens                                          0
tot_hi_cred_lim                                    0
total_bal_ex_mort                                  0
total_bc_limit                                     0
total_il_high_credit_limit                         0
mort_acc                                           0
mo_sin_rcnt_tl                                     0
mo_sin_rcnt_rev_tl_op                              0
mo_sin_old_rev_tl_op                               0
policy_code                                        0
application_type                                   0
acc_now_delinq                                     0
tot_coll_amt                                       0
tot_cur_bal                                        0
open_acc_6m                                        0
open_act_il                                        0
hardship_flag                                      0
open_il_24m                                        0
total_bal_il                                       0
open_rv_12m                                        0
open_rv_24m                                        0
max_bal_bc                                         0
total_rev_hi_lim                                   0
total_cu_tl                                        0
inq_last_12m                                       0
acc_open_past_24mths                               0
chargeoff_within_12_mths                           0
delinq_amnt                                        0
inq_fi                                             0
dtype: int64

In [31]:
df_new = df.drop(columns=['id', 'member_id', 'desc', 'url'])
df_new.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,10000,10000,10000.0,36 months,10.33%,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8289.30,8289.30,2261.00,2261.00,1710.70,550.30,0.0,0.0,0.0,Jul-2019,324.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,4000,4000,4000.0,36 months,23.40%,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3423.38,3423.38,1081.96,1081.96,576.62,505.34,0.0,0.0,0.0,Jul-2019,155.68,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,5000,5000,5000.0,36 months,17.97%,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (31-120 days),n,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.96,895.96,543.83,352.13,0.0,0.0,0.0,Jun-2019,180.69,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,23000,23000,23000.0,60 months,20.89%,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21353.16,21353.16,4307.45,4307.45,1646.84,2660.61,0.0,0.0,0.0,Jul-2019,620.81,Sep-2019,Aug-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,8000,8000,8000.0,36 months,23.40%,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,6846.83,6846.83,2163.85,2163.85,1153.17,1010.68,0.0,0.0,0.0,Jul-2019,311.35,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_new.isnull().sum().sort_values(ascending=False)

orig_projected_additional_accrued_interest    128386
hardship_loan_status                          128385
hardship_dpd                                  128385
hardship_reason                               128385
hardship_status                               128385
deferral_term                                 128385
hardship_amount                               128385
hardship_start_date                           128385
hardship_end_date                             128385
payment_plan_start_date                       128385
hardship_length                               128385
hardship_type                                 128385
hardship_payoff_balance_amount                128385
hardship_last_payment_amount                  128385
settlement_percentage                         128301
debt_settlement_flag_date                     128301
settlement_status                             128301
settlement_date                               128301
settlement_amount                             128301
settlement_term                               128301
sec_app_mths_since_last_major_derog           123258
verification_status_joint                     113564
mths_since_last_record                        112962
sec_app_revol_util                            111888
annual_inc_joint                              111630
sec_app_collections_12_mths_ex_med            111630
dti_joint                                     111630
revol_bal_joint                               111630
sec_app_earliest_cr_line                      111630
sec_app_inq_last_6mths                        111630
sec_app_mort_acc                              111630
sec_app_open_acc                              111630
sec_app_open_act_il                           111630
sec_app_num_rev_accts                         111630
sec_app_chargeoff_within_12_mths              111630
mths_since_recent_bc_dlq                      103243
mths_since_last_major_derog                    99232
mths_since_recent_revol_delinq                 91630
mths_since_last_delinq                         72196
emp_title                                      20947
il_util                                        20274
next_pymnt_d                                   16123
mths_since_recent_inq                          16047
emp_length                                     11704
mo_sin_old_il_acct                              4478
mths_since_rcnt_il                              4478
num_tl_120dpd_2m                                2859
bc_util                                         1754
percent_bc_gt_75                                1692
bc_open_to_buy                                  1691
mths_since_recent_bc                            1591
dti                                              237
last_pymnt_d                                     159
revol_util                                       156
all_util                                          37
avg_cur_bal                                       13
last_credit_pull_d                                 1
out_prncp_inv                                      0
total_pymnt                                        0
total_pymnt_inv                                    0
out_prncp                                          0
total_rec_prncp                                    0
total_rec_late_fee                                 0
initial_list_status                                0
recoveries                                         0
total_acc                                          0
collection_recovery_fee                            0
last_pymnt_amnt                                    0
total_rec_int                                      0
loan_status                                        0
revol_bal                                          0
verification_status                                0
funded_amnt                                        0
funded_amnt_inv                                    0
term                                               0
int_rate                                           0
installment                                        0
grade                                              0
sub_grade                                          0
home_ownership                                     0
annual_inc                                         0
issue_d                                            0
pub_rec                                            0
pymnt_plan                                         0
purpose                                            0
title                                              0
zip_code                                           0
addr_state                                         0
delinq_2yrs                                        0
earliest_cr_line                                   0
inq_last_6mths                                     0
open_acc                                           0
collections_12_mths_ex_med                         0
inq_last_12m                                       0
policy_code                                        0
num_tl_90g_dpd_24m                                 0
num_actv_rev_tl                                    0
num_bc_sats                                        0
num_bc_tl                                          0
num_il_tl                                          0
num_op_rev_tl                                      0
num_rev_accts                                      0
num_rev_tl_bal_gt_0                                0
num_sats                                           0
num_tl_30dpd                                       0
num_tl_op_past_12m                                 0
application_type                                   0
pct_tl_nvr_dlq                                     0
pub_rec_bankruptcies                               0
tax_liens                                          0
tot_hi_cred_lim                                    0
total_bal_ex_mort                                  0
total_bc_limit                                     0
total_il_high_credit_limit                         0
hardship_flag                                      0
debt_settlement_flag                               0
num_actv_bc_tl                                     0
num_accts_ever_120_pd                              0
mort_acc                                           0
mo_sin_rcnt_tl                                     0
acc_now_delinq                                     0
tot_coll_amt                                       0
tot_cur_bal                                        0
open_acc_6m                                        0
open_act_il                                        0
open_il_12m                                        0
open_il_24m                                        0
total_bal_il                                       0
open_rv_12m                                        0
open_rv_24m                                        0
max_bal_bc                                         0
total_rev_hi_lim                                   0
inq_fi                                             0
total_cu_tl                                        0
acc_open_past_24mths                               0
chargeoff_within_12_mths                           0
delinq_amnt                                        0
mo_sin_old_rev_tl_op                               0
mo_sin_rcnt_rev_tl_op                              0
loan_amnt                                          0
dtype: int64

In [14]:
df_new['int_rate']

0          10.33%
1          23.40%
2          17.97%
3          20.89%
4          23.40%
5          11.80%
6          12.98%
7          18.94%
8          13.56%
9          13.56%
10         19.92%
11         17.97%
12         26.31%
13         14.47%
14         23.40%
15         23.40%
16         20.89%
17         16.91%
18         20.89%
19         14.47%
20         13.56%
21         14.47%
22         12.98%
23         23.40%
24         11.80%
25         20.89%
26         26.31%
27         16.14%
28         18.94%
29         15.02%
30         17.97%
31         13.56%
32         17.97%
33         12.98%
34         11.80%
35         10.72%
36         12.98%
37         11.80%
38         14.47%
39         10.72%
40         11.80%
41         23.40%
42         20.89%
43         19.92%
44         10.33%
45          6.46%
46         14.47%
47         11.31%
48         17.97%
49         15.02%
50          8.81%
51         15.02%
52         16.91%
53         14.47%
54         25.34%
55         14.47%
56         12.98%
57         10.72%
58         19.92%
59         17.97%
60         12.98%
61         16.14%
62         10.33%
63         20.89%
64         17.97%
65         17.97%
66         12.98%
67         23.40%
68         14.47%
69         19.92%
70         14.47%
71         16.91%
72          6.46%
73         10.33%
74         13.56%
75         14.47%
76         10.33%
77         12.98%
78         12.98%
79         16.14%
80         15.02%
81         27.27%
82         16.91%
83         14.47%
84         15.02%
85         13.56%
86         16.91%
87         12.98%
88         14.47%
89         14.47%
90         17.97%
91         16.14%
92         11.80%
93         18.94%
94         11.80%
95         11.80%
96         18.94%
97         11.31%
98          7.56%
99         18.94%
100        11.31%
101        23.40%
102        11.31%
103        10.72%
104        14.47%
105        14.47%
106        16.91%
107        22.35%
108        12.98%
109        16.14%
110        16.14%
111        17.97%
112        14.47%
113        12.98%
114        10.72%
115        11.31%
116        10.33%
117        18.94%
118        15.02%
119        16.14%
120        13.56%
121        22.35%
122        15.02%
123        14.47%
124        10.72%
125        16.14%
126        15.02%
127        19.92%
128        14.47%
129        11.31%
130        12.98%
131        27.27%
132        17.97%
133        15.02%
134        16.14%
135        12.98%
136        15.02%
137        18.94%
138        16.14%
139        11.31%
140        26.31%
141        11.80%
142        15.02%
143        27.27%
144        26.31%
145        14.47%
146        15.02%
147        14.47%
148        15.02%
149        16.14%
150        11.31%
151        27.27%
152        11.31%
153        23.40%
154        10.33%
155        18.94%
156        11.31%
157        16.14%
158        12.98%
159        10.72%
160        17.97%
161        23.40%
162        14.47%
163        13.56%
164        10.72%
165        11.80%
166        18.94%
167        13.56%
168        11.31%
169         7.56%
170        10.72%
171        11.80%
172        17.97%
173        16.14%
174        17.97%
175        12.98%
176        11.31%
177        20.89%
178         8.19%
179        20.89%
180        16.91%
181        22.35%
182         8.81%
183        23.40%
184        11.31%
185        15.02%
186        23.40%
187        16.14%
188        10.33%
189        15.02%
190        14.47%
191        23.40%
192        10.72%
193        16.14%
194        13.56%
195        14.47%
196        14.47%
197         8.81%
198        10.33%
199        18.94%
200        15.02%
201        30.75%
202         8.19%
203         6.46%
204        13.56%
205         8.19%
206        16.14%
207        10.72%
208        16.91%
209        10.72%
210        15.02%
211        14.47%
212        16.14%
213        16.91%
214        13.56%
215        11.31%
216        16.14%
217        15.02%
218        16.14%
219        15.02%
220        17.97%
221        18.94%
222        16.91%
223        11.80%
224        14.47%
225        11.31%
226        14.47%
227        16.14%
228        20.89%
229        17.97%
230        16.14%
231        10.33%
232         8.81%
233        14.47%
234        16.14%
235        13.56%
236        10.72%
237        14.47%
238        11.31%
239        17.97%
240        12.98%
241        16.14%
242        22.35%
243         8.19%
244        20.89%
245         6.46%
246        27.27%
247        12.98%
248        15.02%
249        17.97%
           ...
128162     28.72%
128163     22.35%
128164      7.21%
128165     19.92%
128166     11.55%
128167     20.89%
128168      8.46%
128169      7.84%
128170     16.91%
128171     15.02%
128172     16.14%
128173     10.08%
128174     13.56%
128175      8.46%
128176      6.11%
128177      6.67%
128178     19.92%
128179     12.73%
128180     10.08%
128181     22.35%
128182     12.73%
128183     11.55%
128184      7.21%
128185     13.56%
128186      6.11%
128187     13.56%
128188     16.14%
128189     18.94%
128190      8.46%
128191     14.47%
128192     28.72%
128193     14.47%
128194      7.84%
128195     10.08%
128196     23.40%
128197      7.21%
128198      6.67%
128199      6.11%
128200     28.72%
128201      6.67%
128202     12.73%
128203     11.55%
128204      6.67%
128205      6.11%
128206      7.84%
128207     10.47%
128208     25.34%
128209     13.56%
128210      7.21%
128211      6.11%
128212      7.21%
128213     22.35%
128214     19.92%
128215      8.46%
128216      6.11%
128217      6.67%
128218      6.11%
128219      6.11%
128220      7.84%
128221     11.55%
128222     10.47%
128223     11.06%
128224     10.47%
128225      8.46%
128226      6.67%
128227     12.73%
128228      6.11%
128229      6.11%
128230     16.14%
128231     16.91%
128232     24.37%
128233     12.73%
128234     11.06%
128235     16.14%
128236     18.94%
128237      6.11%
128238     16.14%
128239     13.56%
128240      6.11%
128241     22.35%
128242      6.11%
128243     27.27%
128244     11.55%
128245      6.11%
128246      6.11%
128247      7.21%
128248      7.21%
128249      6.11%
128250      8.46%
128251      6.11%
128252      7.84%
128253      7.21%
128254     26.31%
128255     16.91%
128256     28.72%
128257     29.69%
128258      7.21%
128259      7.84%
128260      7.21%
128261     11.06%
128262     25.34%
128263      6.11%
128264     11.06%
128265     16.91%
128266     17.97%
128267     10.08%
128268     27.27%
128269      6.67%
128270      7.84%
128271     15.02%
128272     11.06%
128273     14.47%
128274     18.94%
128275      7.21%
128276     13.56%
128277     15.02%
128278      7.84%
128279     19.92%
128280      7.21%
128281      8.46%
128282     18.94%
128283     13.56%
128284      6.11%
128285     11.06%
128286     14.47%
128287      7.21%
128288     14.47%
128289      6.67%
128290      8.46%
128291     16.91%
128292     13.56%
128293      6.67%
128294      7.84%
128295      6.67%
128296     14.47%
128297     15.02%
128298      6.11%
128299     25.34%
128300     16.14%
128301     23.40%
128302      7.21%
128303      6.11%
128304     12.73%
128305      7.84%
128306     10.47%
128307     15.02%
128308     24.37%
128309     10.08%
128310     22.35%
128311      7.84%
128312     27.27%
128313     15.02%
128314     22.35%
128315      6.11%
128316     22.35%
128317      7.84%
128318      6.11%
128319     17.97%
128320     22.35%
128321     15.02%
128322     17.97%
128323     11.55%
128324     10.08%
128325      6.11%
128326      6.11%
128327     17.97%
128328     16.14%
128329     23.40%
128330     20.89%
128331     13.56%
128332      6.11%
128333     15.02%
128334     18.94%
128335      7.84%
128336      7.21%
128337      7.84%
128338     11.55%
128339     24.37%
128340      7.21%
128341     19.92%
128342     14.47%
128343     24.37%
128344     12.73%
128345      7.84%
128346      7.21%
128347      7.84%
128348      7.84%
128349     15.02%
128350     16.91%
128351     27.27%
128352     10.08%
128353     11.55%
128354      7.21%
128355      6.11%
128356     13.56%
128357     27.27%
128358     11.55%
128359     11.06%
128360      7.21%
128361     17.97%
128362     27.27%
128363     11.55%
128364     11.06%
128365      8.46%
128366      7.84%
128367      6.11%
128368      8.46%
128369     14.47%
128370     14.47%
128371     13.56%
128372     17.97%
128373      7.84%
128374     22.35%
128375     11.55%
128376     16.91%
128377     11.06%
128378     13.56%
128379     27.27%
128380      6.67%
128381      7.84%
128382     17.97%
128383     16.91%
128384     13.56%
128385     17.97%
128386     26.31%
128387     11.55%
128388      8.46%
128389     11.55%
128390     19.92%
128391      6.67%
128392     26.31%
128393     16.91%
128394      6.11%
128395     11.55%
128396     15.02%
128397     15.02%
128398     18.94%
128399     15.02%
128400     15.02%
128401     11.55%
128402     22.35%
128403     16.14%
128404     16.14%
128405      7.84%
128406     13.56%
128407     15.02%
128408     15.02%
128409     13.56%
128410     11.06%
128411     16.91%
Name: int_rate, Length: 128412, dtype: object

In [15]:
df_new.dtypes

loan_amnt                                       int64
funded_amnt                                     int64
funded_amnt_inv                               float64
term                                           object
int_rate                                       object
installment                                   float64
grade                                          object
sub_grade                                      object
emp_title                                      object
emp_length                                     object
home_ownership                                 object
annual_inc                                    float64
verification_status                            object
issue_d                                        object
loan_status                                    object
pymnt_plan                                     object
purpose                                        object
title                                          object
zip_code                                       object
addr_state                                     object
dti                                           float64
delinq_2yrs                                     int64
earliest_cr_line                               object
inq_last_6mths                                  int64
mths_since_last_delinq                        float64
mths_since_last_record                        float64
open_acc                                        int64
pub_rec                                         int64
revol_bal                                       int64
revol_util                                     object
total_acc                                       int64
initial_list_status                            object
out_prncp                                     float64
out_prncp_inv                                 float64
total_pymnt                                   float64
total_pymnt_inv                               float64
total_rec_prncp                               float64
total_rec_int                                 float64
total_rec_late_fee                            float64
recoveries                                    float64
collection_recovery_fee                       float64
last_pymnt_d                                   object
last_pymnt_amnt                               float64
next_pymnt_d                                   object
last_credit_pull_d                             object
collections_12_mths_ex_med                      int64
mths_since_last_major_derog                   float64
policy_code                                     int64
application_type                               object
annual_inc_joint                              float64
dti_joint                                     float64
verification_status_joint                      object
acc_now_delinq                                  int64
tot_coll_amt                                    int64
tot_cur_bal                                     int64
open_acc_6m                                     int64
open_act_il                                     int64
open_il_12m                                     int64
open_il_24m                                     int64
mths_since_rcnt_il                            float64
total_bal_il                                    int64
il_util                                       float64
open_rv_12m                                     int64
open_rv_24m                                     int64
max_bal_bc                                      int64
all_util                                      float64
total_rev_hi_lim                                int64
inq_fi                                          int64
total_cu_tl                                     int64
inq_last_12m                                    int64
acc_open_past_24mths                            int64
avg_cur_bal                                   float64
bc_open_to_buy                                float64
bc_util                                       float64
chargeoff_within_12_mths                        int64
delinq_amnt                                     int64
mo_sin_old_il_acct                            float64
mo_sin_old_rev_tl_op                            int64
mo_sin_rcnt_rev_tl_op                           int64
mo_sin_rcnt_tl                                  int64
mort_acc                                        int64
mths_since_recent_bc                          float64
mths_since_recent_bc_dlq                      float64
mths_since_recent_inq                         float64
mths_since_recent_revol_delinq                float64
num_accts_ever_120_pd                           int64
num_actv_bc_tl                                  int64
num_actv_rev_tl                                 int64
num_bc_sats                                     int64
num_bc_tl                                       int64
num_il_tl                                       int64
num_op_rev_tl                                   int64
num_rev_accts                                   int64
num_rev_tl_bal_gt_0                             int64
num_sats                                        int64
num_tl_120dpd_2m                              float64
num_tl_30dpd                                    int64
num_tl_90g_dpd_24m                              int64
num_tl_op_past_12m                              int64
pct_tl_nvr_dlq                                float64
percent_bc_gt_75                              float64
pub_rec_bankruptcies                            int64
tax_liens                                       int64
tot_hi_cred_lim                                 int64
total_bal_ex_mort                               int64
total_bc_limit                                  int64
total_il_high_credit_limit                      int64
revol_bal_joint                               float64
sec_app_earliest_cr_line                       object
sec_app_inq_last_6mths                        float64
sec_app_mort_acc                              float64
sec_app_open_acc                              float64
sec_app_revol_util                            float64
sec_app_open_act_il                           float64
sec_app_num_rev_accts                         float64
sec_app_chargeoff_within_12_mths              float64
sec_app_collections_12_mths_ex_med            float64
sec_app_mths_since_last_major_derog           float64
hardship_flag                                  object
hardship_type                                  object
hardship_reason                                object
hardship_status                                object
deferral_term                                 float64
hardship_amount                               float64
hardship_start_date                            object
hardship_end_date                              object
payment_plan_start_date                        object
hardship_length                               float64
hardship_dpd                                  float64
hardship_loan_status                           object
orig_projected_additional_accrued_interest    float64
hardship_payoff_balance_amount                float64
hardship_last_payment_amount                  float64
debt_settlement_flag                           object
debt_settlement_flag_date                      object
settlement_status                              object
settlement_date                                object
settlement_amount                             float64
settlement_percentage                         float64
settlement_term                               float64
dtype: object

In [16]:
# understanding string in pandas

# string is list of characters

int_rate = '15.02%'
#int_rate[1:3]

# -1 denotes last character from the string  
int_rate[:-1]

'15.02'

In [17]:
# remove characters at the beginning or end of a string
int_rate = '15.02%'
int_rate.strip('%')

'15.02'

In [18]:
# Remove characters in the middle of a string
int_rate = '14.59%'
int_rate.replace('.', '')

'1459%'

In [19]:
int_rate='15.02%'
type(int_rate.strip('%'))

str

In [20]:
type(float(int_rate.strip('%')))

float

In [21]:
# Write a function that will work on any given cell in a dataframe column
def remove_percent_to_float(string):
  return float(string.strip('%'))

int_rate='35.47%'
remove_percent_to_float(int_rate)

35.47

In [0]:
# Use the apply fn
df_new['int_rate'] = df_new['int_rate'].apply(remove_percent_to_float)

In [23]:
df_new.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,10000,10000,10000.0,36 months,10.33,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8289.30,8289.30,2261.00,2261.00,1710.70,550.30,0.0,0.0,0.0,Jul-2019,324.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,4000,4000,4000.0,36 months,23.40,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3423.38,3423.38,1081.96,1081.96,576.62,505.34,0.0,0.0,0.0,Jul-2019,155.68,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (31-120 days),n,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.96,895.96,543.83,352.13,0.0,0.0,0.0,Jun-2019,180.69,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,23000,23000,23000.0,60 months,20.89,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21353.16,21353.16,4307.45,4307.45,1646.84,2660.61,0.0,0.0,0.0,Jul-2019,620.81,Sep-2019,Aug-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,8000,8000,8000.0,36 months,23.40,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,6846.83,6846.83,2163.85,2163.85,1153.17,1010.68,0.0,0.0,0.0,Jul-2019,311.35,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_new.dtypes

loan_amnt                                       int64
funded_amnt                                     int64
funded_amnt_inv                               float64
term                                           object
int_rate                                      float64
installment                                   float64
grade                                          object
sub_grade                                      object
emp_title                                      object
emp_length                                     object
home_ownership                                 object
annual_inc                                    float64
verification_status                            object
issue_d                                        object
loan_status                                    object
pymnt_plan                                     object
purpose                                        object
title                                          object
zip_code                                       object
addr_state                                     object
dti                                           float64
delinq_2yrs                                     int64
earliest_cr_line                               object
inq_last_6mths                                  int64
mths_since_last_delinq                        float64
mths_since_last_record                        float64
open_acc                                        int64
pub_rec                                         int64
revol_bal                                       int64
revol_util                                     object
total_acc                                       int64
initial_list_status                            object
out_prncp                                     float64
out_prncp_inv                                 float64
total_pymnt                                   float64
total_pymnt_inv                               float64
total_rec_prncp                               float64
total_rec_int                                 float64
total_rec_late_fee                            float64
recoveries                                    float64
collection_recovery_fee                       float64
last_pymnt_d                                   object
last_pymnt_amnt                               float64
next_pymnt_d                                   object
last_credit_pull_d                             object
collections_12_mths_ex_med                      int64
mths_since_last_major_derog                   float64
policy_code                                     int64
application_type                               object
annual_inc_joint                              float64
dti_joint                                     float64
verification_status_joint                      object
acc_now_delinq                                  int64
tot_coll_amt                                    int64
tot_cur_bal                                     int64
open_acc_6m                                     int64
open_act_il                                     int64
open_il_12m                                     int64
open_il_24m                                     int64
mths_since_rcnt_il                            float64
total_bal_il                                    int64
il_util                                       float64
open_rv_12m                                     int64
open_rv_24m                                     int64
max_bal_bc                                      int64
all_util                                      float64
total_rev_hi_lim                                int64
inq_fi                                          int64
total_cu_tl                                     int64
inq_last_12m                                    int64
acc_open_past_24mths                            int64
avg_cur_bal                                   float64
bc_open_to_buy                                float64
bc_util                                       float64
chargeoff_within_12_mths                        int64
delinq_amnt                                     int64
mo_sin_old_il_acct                            float64
mo_sin_old_rev_tl_op                            int64
mo_sin_rcnt_rev_tl_op                           int64
mo_sin_rcnt_tl                                  int64
mort_acc                                        int64
mths_since_recent_bc                          float64
mths_since_recent_bc_dlq                      float64
mths_since_recent_inq                         float64
mths_since_recent_revol_delinq                float64
num_accts_ever_120_pd                           int64
num_actv_bc_tl                                  int64
num_actv_rev_tl                                 int64
num_bc_sats                                     int64
num_bc_tl                                       int64
num_il_tl                                       int64
num_op_rev_tl                                   int64
num_rev_accts                                   int64
num_rev_tl_bal_gt_0                             int64
num_sats                                        int64
num_tl_120dpd_2m                              float64
num_tl_30dpd                                    int64
num_tl_90g_dpd_24m                              int64
num_tl_op_past_12m                              int64
pct_tl_nvr_dlq                                float64
percent_bc_gt_75                              float64
pub_rec_bankruptcies                            int64
tax_liens                                       int64
tot_hi_cred_lim                                 int64
total_bal_ex_mort                               int64
total_bc_limit                                  int64
total_il_high_credit_limit                      int64
revol_bal_joint                               float64
sec_app_earliest_cr_line                       object
sec_app_inq_last_6mths                        float64
sec_app_mort_acc                              float64
sec_app_open_acc                              float64
sec_app_revol_util                            float64
sec_app_open_act_il                           float64
sec_app_num_rev_accts                         float64
sec_app_chargeoff_within_12_mths              float64
sec_app_collections_12_mths_ex_med            float64
sec_app_mths_since_last_major_derog           float64
hardship_flag                                  object
hardship_type                                  object
hardship_reason                                object
hardship_status                                object
deferral_term                                 float64
hardship_amount                               float64
hardship_start_date                            object
hardship_end_date                              object
payment_plan_start_date                        object
hardship_length                               float64
hardship_dpd                                  float64
hardship_loan_status                           object
orig_projected_additional_accrued_interest    float64
hardship_payoff_balance_amount                float64
hardship_last_payment_amount                  float64
debt_settlement_flag                           object
debt_settlement_flag_date                      object
settlement_status                              object
settlement_date                                object
settlement_amount                             float64
settlement_percentage                         float64
settlement_term                               float64
dtype: object

In [0]:
#List Comprehension example
int_list = ['15.02%', '13.56%', '16.91%']

In [26]:
[remove_percent_to_float(item) for item in int_list]

[15.02, 13.56, 16.91]

In [32]:
# load df and df-new before this command
list(df_new['int_rate'])

[' 10.33%',
 ' 23.40%',
 ' 17.97%',
 ' 20.89%',
 ' 23.40%',
 ' 11.80%',
 ' 12.98%',
 ' 18.94%',
 ' 13.56%',
 ' 13.56%',
 ' 19.92%',
 ' 17.97%',
 ' 26.31%',
 ' 14.47%',
 ' 23.40%',
 ' 23.40%',
 ' 20.89%',
 ' 16.91%',
 ' 20.89%',
 ' 14.47%',
 ' 13.56%',
 ' 14.47%',
 ' 12.98%',
 ' 23.40%',
 ' 11.80%',
 ' 20.89%',
 ' 26.31%',
 ' 16.14%',
 ' 18.94%',
 ' 15.02%',
 ' 17.97%',
 ' 13.56%',
 ' 17.97%',
 ' 12.98%',
 ' 11.80%',
 ' 10.72%',
 ' 12.98%',
 ' 11.80%',
 ' 14.47%',
 ' 10.72%',
 ' 11.80%',
 ' 23.40%',
 ' 20.89%',
 ' 19.92%',
 ' 10.33%',
 '  6.46%',
 ' 14.47%',
 ' 11.31%',
 ' 17.97%',
 ' 15.02%',
 '  8.81%',
 ' 15.02%',
 ' 16.91%',
 ' 14.47%',
 ' 25.34%',
 ' 14.47%',
 ' 12.98%',
 ' 10.72%',
 ' 19.92%',
 ' 17.97%',
 ' 12.98%',
 ' 16.14%',
 ' 10.33%',
 ' 20.89%',
 ' 17.97%',
 ' 17.97%',
 ' 12.98%',
 ' 23.40%',
 ' 14.47%',
 ' 19.92%',
 ' 14.47%',
 ' 16.91%',
 '  6.46%',
 ' 10.33%',
 ' 13.56%',
 ' 14.47%',
 ' 10.33%',
 ' 12.98%',
 ' 12.98%',
 ' 16.14%',
 ' 15.02%',
 ' 27.27%',
 ' 16.91%',
 ' 14.47%',
 ' 15.02%',
 ' 13.56%',
 ' 16.91%',
 ' 12.98%',
 ' 14.47%',
 ' 14.47%',
 ' 17.97%',
 ' 16.14%',
 ' 11.80%',
 ' 18.94%',
 ' 11.80%',
 ' 11.80%',
 ' 18.94%',
 ' 11.31%',
 '  7.56%',
 ' 18.94%',
 ' 11.31%',
 ' 23.40%',
 ' 11.31%',
 ' 10.72%',
 ' 14.47%',
 ' 14.47%',
 ' 16.91%',
 ' 22.35%',
 ' 12.98%',
 ' 16.14%',
 ' 16.14%',
 ' 17.97%',
 ' 14.47%',
 ' 12.98%',
 ' 10.72%',
 ' 11.31%',
 ' 10.33%',
 ' 18.94%',
 ' 15.02%',
 ' 16.14%',
 ' 13.56%',
 ' 22.35%',
 ' 15.02%',
 ' 14.47%',
 ' 10.72%',
 ' 16.14%',
 ' 15.02%',
 ' 19.92%',
 ' 14.47%',
 ' 11.31%',
 ' 12.98%',
 ' 27.27%',
 ' 17.97%',
 ' 15.02%',
 ' 16.14%',
 ' 12.98%',
 ' 15.02%',
 ' 18.94%',
 ' 16.14%',
 ' 11.31%',
 ' 26.31%',
 ' 11.80%',
 ' 15.02%',
 ' 27.27%',
 ' 26.31%',
 ' 14.47%',
 ' 15.02%',
 ' 14.47%',
 ' 15.02%',
 ' 16.14%',
 ' 11.31%',
 ' 27.27%',
 ' 11.31%',
 ' 23.40%',
 ' 10.33%',
 ' 18.94%',
 ' 11.31%',
 ' 16.14%',
 ' 12.98%',
 ' 10.72%',
 ' 17.97%',
 ' 23.40%',
 ' 14.47%',
 ' 13.56%',
 ' 10.72%',
 ' 11.80%',
 ' 18.94%',
 ' 13.56%',
 ' 11.31%',
 '  7.56%',
 ' 10.72%',
 ' 11.80%',
 ' 17.97%',
 ' 16.14%',
 ' 17.97%',
 ' 12.98%',
 ' 11.31%',
 ' 20.89%',
 '  8.19%',
 ' 20.89%',
 ' 16.91%',
 ' 22.35%',
 '  8.81%',
 ' 23.40%',
 ' 11.31%',
 ' 15.02%',
 ' 23.40%',
 ' 16.14%',
 ' 10.33%',
 ' 15.02%',
 ' 14.47%',
 ' 23.40%',
 ' 10.72%',
 ' 16.14%',
 ' 13.56%',
 ' 14.47%',
 ' 14.47%',
 '  8.81%',
 ' 10.33%',
 ' 18.94%',
 ' 15.02%',
 ' 30.75%',
 '  8.19%',
 '  6.46%',
 ' 13.56%',
 '  8.19%',
 ' 16.14%',
 ' 10.72%',
 ' 16.91%',
 ' 10.72%',
 ' 15.02%',
 ' 14.47%',
 ' 16.14%',
 ' 16.91%',
 ' 13.56%',
 ' 11.31%',
 ' 16.14%',
 ' 15.02%',
 ' 16.14%',
 ' 15.02%',
 ' 17.97%',
 ' 18.94%',
 ' 16.91%',
 ' 11.80%',
 ' 14.47%',
 ' 11.31%',
 ' 14.47%',
 ' 16.14%',
 ' 20.89%',
 ' 17.97%',
 ' 16.14%',
 ' 10.33%',
 '  8.81%',
 ' 14.47%',
 ' 16.14%',
 ' 13.56%',
 ' 10.72%',
 ' 14.47%',
 ' 11.31%',
 ' 17.97%',
 ' 12.98%',
 ' 16.14%',
 ' 22.35%',
 '  8.19%',
 ' 20.89%',
 '  6.46%',
 ' 27.27%',
 ' 12.98%',
 ' 15.02%',
 ' 17.97%',
 ' 10.33%',
 ' 18.94%',
 ' 16.91%',
 '  8.19%',
 ' 10.33%',
 '  7.02%',
 '  8.19%',
 '  7.56%',
 ' 11.80%',
 ' 11.80%',
 ' 10.33%',
 ' 22.35%',
 ' 11.31%',
 ' 10.33%',
 ' 14.47%',
 ' 18.94%',
 ' 12.98%',
 ' 10.33%',
 '  6.46%',
 ' 19.92%',
 ' 13.56%',
 ' 15.02%',
 ' 13.56%',
 ' 10.72%',
 '  8.19%',
 ' 11.80%',
 ' 14.47%',
 ' 22.35%',
 ' 19.92%',
 ' 14.47%',
 '  8.19%',
 '  7.56%',
 ' 18.94%',
 ' 10.72%',
 ' 20.89%',
 ' 14.47%',
 ' 16.91%',
 ' 10.72%',
 '  7.56%',
 '  8.81%',
 '  7.02%',
 '  8.81%',
 ' 13.56%',
 '  8.19%',
 '  7.02%',
 ' 16.14%',
 '  8.19%',
 ' 12.98%',
 ' 23.40%',
 ' 17.97%',
 '  7.02%',
 '  8.81%',
 ' 17.97%',
 ' 12.98%',
 ' 11.31%',
 ' 15.02%',
 '  8.81%',
 ' 20.89%',
 '  8.19%',
 ' 18.94%',
 ' 22.35%',
 '  8.81%',
 ' 13.56%',
 ' 15.02%',
 ' 16.14%',
 ' 11.80%',
 '  7.02%',
 '  8.19%',
 ' 11.80%',
 ' 16.91%',
 ' 11.31%',
 '  6.46%',
 '  7.02%',
 '  8.19%',
 ' 10.33%',
 ' 11.80%',
 ' 14.47%',
 ' 10.33%',
 ' 18.94%',
 ' 14.47%',
 '  7.02%',
 ' 23.40%',
 '  6.46%',
 ' 11.80%',
 ' 14.47%',
 '  8.19%',
 ' 16.91%',
 ' 20.89%',
 ' 16.91%',
 '  8.19%',
 ' 10.72%',
 '  8.19%',
 '  6.46%',
 ' 11.80%',
 '  8.81%',
 '  7.02%',
 ' 10.72%',
 ' 18.94%',
 ' 13.56%',
 ' 12.98%',
 '  6.46%',
 '  8.19%',
 ' 11.80%',
 ' 15.02%',
 ' 16.14%',
 ' 16.91%',
 '  7.56%',
 '  7.02%',
 ' 10.72%',
 ' 10.72%',
 ' 16.14%',
 ' 15.02%',
 '  8.19%',
 '  8.19%',
 '  8.19%',
 ' 22.35%',
 '  8.81%',
 '  7.56%',
 ' 10.72%',
 ' 12.98%',
 ' 15.02%',
 ' 10.33%',
 ' 11.80%',
 ' 19.92%',
 ' 14.47%',
 ' 17.97%',
 '  8.19%',
 ' 15.02%',
 '  7.56%',
 '  8.81%',
 '  7.02%',
 ' 10.72%',
 ' 17.97%',
 '  8.81%',
 ' 11.31%',
 '  8.81%',
 ' 18.94%',
 '  7.02%',
 ' 19.92%',
 ' 12.98%',
 ' 23.40%',
 ' 14.47%',
 ' 13.56%',
 ' 19.92%',
 ' 11.80%',
 '  8.19%',
 '  7.02%',
 ' 10.72%',
 ' 19.92%',
 ' 15.02%',
 '  6.46%',
 ' 12.98%',
 '  7.56%',
 ' 11.31%',
 ' 17.97%',
 '  7.56%',
 ' 16.14%',
 ' 11.31%',
 ' 24.37%',
 ' 16.91%',
 ' 10.72%',
 '  8.81%',
 ' 11.80%',
 '  8.19%',
 '  8.81%',
 ' 15.02%',
 ' 23.40%',
 '  6.46%',
 ' 10.33%',
 '  8.81%',
 ' 22.35%',
 ' 11.80%',
 ' 15.02%',
 ' 19.92%',
 ' 13.56%',
 ' 18.94%',
 '  8.19%',
 ' 11.31%',
 ' 11.80%',
 ' 11.80%',
 ' 13.56%',
 '  8.81%',
 ' 12.98%',
 ' 11.80%',
 ' 11.80%',
 ' 11.80%',
 ' 16.14%',
 '  8.19%',
 ' 10.33%',
 '  6.46%',
 ' 12.98%',
 '  8.19%',
 ' 10.72%',
 ' 24.37%',
 '  6.46%',
 ' 11.80%',
 '  8.81%',
 ' 13.56%',
 '  7.02%',
 ' 10.33%',
 '  7.02%',
 ' 12.98%',
 ' 10.72%',
 ' 10.33%',
 ' 16.14%',
 '  8.19%',
 '  8.19%',
 '  8.19%',
 ' 10.33%',
 ' 19.92%',
 ' 10.72%',
 ' 10.33%',
 ' 13.56%',
 ' 10.33%',
 '  8.81%',
 ' 23.40%',
 ' 16.91%',
 '  8.19%',
 '  7.02%',
 ' 10.72%',
 ' 13.56%',
 ' 11.80%',
 ' 10.33%',
 ' 17.97%',
 ' 15.02%',
 '  7.56%',
 '  8.19%',
 ' 11.80%',
 ' 18.94%',
 ' 14.47%',
 '  8.19%',
 ' 16.91%',
 '  6.46%',
 ' 15.02%',
 ' 16.14%',
 '  7.56%',
 ' 13.56%',
 ' 12.98%',
 ' 15.02%',
 '  6.46%',
 ' 10.33%',
 ' 11.80%',
 ' 11.31%',
 '  8.81%',
 '  6.46%',
 '  8.81%',
 '  7.56%',
 ' 11.31%',
 ' 20.89%',
 '  7.02%',
 ' 16.91%',
 ' 23.40%',
 ' 13.56%',
 ' 11.80%',
 '  8.81%',
 ' 17.97%',
 ' 24.37%',
 ' 11.80%',
 '  8.19%',
 ' 11.80%',
 ' 27.27%',
 ' 26.31%',
 ' 11.80%',
 ' 22.35%',
 ' 10.72%',
 '  8.81%',
 ' 27.27%',
 '  7.56%',
 '  7.02%',
 '  7.56%',
 '  6.46%',
 ' 16.14%',
 ' 10.33%',
 '  7.02%',
 ' 11.80%',
 ' 11.31%',
 ' 19.92%',
 ' 18.94%',
 ' 13.56%',
 '  6.46%',
 '  8.81%',
 ' 15.02%',
 '  8.81%',
 ' 10.72%',
 ' 11.80%',
 ' 11.80%',
 ' 10.33%',
 ' 10.72%',
 ' 15.02%',
 '  6.46%',
 '  7.02%',
 ' 11.80%',
 '  7.56%',
 ' 17.97%',
 '  8.19%',
 ' 11.80%',
 ' 19.92%',
 ' 16.91%',
 '  6.46%',
 ' 16.14%',
 ' 11.31%',
 ' 19.92%',
 ' 13.56%',
 ' 12.98%',
 ' 16.91%',
 ' 11.80%',
 ' 12.98%',
 ' 15.02%',
 ' 11.31%',
 ' 16.91%',
 ' 16.91%',
 ' 16.14%',
 '  8.81%',
 '  8.19%',
 '  7.02%',
 ' 16.91%',
 '  8.81%',
 ' 17.97%',
 '  8.81%',
 ' 13.56%',
 ' 10.72%',
 ' 10.33%',
 ' 14.47%',
 '  7.56%',
 '  8.19%',
 '  8.19%',
 ' 11.80%',
 '  7.02%',
 ' 23.40%',
 ' 10.72%',
 ' 16.14%',
 '  7.02%',
 '  8.19%',
 '  6.46%',
 ' 16.14%',
 ' 16.91%',
 ' 12.98%',
 '  8.19%',
 '  7.02%',
 ' 15.02%',
 '  6.46%',
 ' 11.80%',
 ' 11.80%',
 '  8.19%',
 '  8.81%',
 ' 10.72%',
 '  8.19%',
 ' 10.72%',
 '  8.19%',
 ' 12.98%',
 '  6.46%',
 ' 27.27%',
 ' 11.80%',
 ' 23.40%',
 ' 12.98%',
 ' 18.94%',
 ' 23.40%',
 ' 14.47%',
 '  7.02%',
 ' 14.47%',
 ' 10.33%',
 ' 18.94%',
 ' 18.94%',
 ' 17.97%',
 '  6.46%',
 ' 22.35%',
 '  8.81%',
 '  8.19%',
 ' 11.80%',
 '  8.81%',
 ' 11.80%',
 ' 17.97%',
 ' 19.92%',
 ' 16.14%',
 ' 14.47%',
 ' 14.47%',
 '  7.02%',
 '  6.46%',
 '  8.81%',
 '  8.81%',
 ' 16.14%',
 '  7.56%',
 ' 11.80%',
 '  6.46%',
 ' 13.56%',
 '  8.81%',
 ' 16.14%',
 '  6.46%',
 ' 16.14%',
 '  6.46%',
 '  7.56%',
 '  7.56%',
 ' 10.72%',
 ' 15.02%',
 ' 13.56%',
 '  6.46%',
 ' 18.94%',
 ' 26.31%',
 '  8.19%',
 ' 11.31%',
 ' 12.98%',
 ' 13.56%',
 '  8.81%',
 ' 11.31%',
 ' 12.98%',
 ' 11.80%',
 ' 15.02%',
 '  7.02%',
 '  6.46%',
 ' 11.80%',
 '  7.56%',
 ' 11.31%',
 '  6.46%',
 ' 11.80%',
 '  8.81%',
 ' 10.72%',
 ' 12.98%',
 ' 20.89%',
 '  7.56%',
 ' 11.31%',
 ' 10.72%',
 ' 16.14%',
 '  8.81%',
 '  6.46%',
 ' 15.02%',
 ' 12.98%',
 ' 19.92%',
 '  8.81%',
 '  6.46%',
 ' 15.02%',
 '  8.19%',
 '  6.46%',
 ' 16.14%',
 ' 14.47%',
 '  6.46%',
 ' 11.31%',
 ' 26.31%',
 '  8.19%',
 '  7.02%',
 ' 13.56%',
 ' 23.40%',
 ' 14.47%',
 ' 10.33%',
 ' 10.33%',
 '  7.56%',
 ' 10.72%',
 ' 11.31%',
 ' 20.89%',
 ' 11.80%',
 '  6.46%',
 '  7.56%',
 ' 10.33%',
 '  8.81%',
 ' 17.97%',
 ' 10.72%',
 ' 26.31%',
 '  7.02%',
 '  8.19%',
 ' 13.56%',
 '  6.46%',
 ' 10.33%',
 '  7.02%',
 '  8.19%',
 '  6.46%',
 ' 10.33%',
 ' 15.02%',
 ' 27.27%',
 '  8.81%',
 ' 15.02%',
 ' 24.37%',
 ' 14.47%',
 '  8.19%',
 '  6.46%',
 ' 13.56%',
 ' 11.31%',
 ' 11.31%',
 ' 11.80%',
 ' 11.80%',
 '  6.46%',
 '  6.46%',
 '  7.56%',
 ' 11.80%',
 ' 12.98%',
 ' 17.97%',
 ' 18.94%',
 ' 16.91%',
 '  6.46%',
 ' 10.33%',
 ' 25.34%',
 ' 11.80%',
 ' 11.31%',
 ' 10.33%',
 ' 14.47%',
 '  6.46%',
 ' 12.98%',
 '  7.02%',
 ' 17.97%',
 '  8.19%',
 ' 12.98%',
 ' 10.33%',
 ' 10.33%',
 '  8.19%',
 ' 22.35%',
 ' 12.98%',
 ' 11.31%',
 ' 16.14%',
 ' 12.98%',
 ' 11.80%',
 ' 10.33%',
 '  6.46%',
 ' 11.80%',
 '  7.56%',
 ' 10.33%',
 '  8.19%',
 ' 12.98%',
 '  8.19%',
 '  8.19%',
 '  8.19%',
 ' 14.47%',
 ' 11.31%',
 '  8.19%',
 ' 10.72%',
 ' 14.47%',
 ' 26.31%',
 ' 10.72%',
 ' 13.56%',
 ' 10.72%',
 '  8.81%',
 ' 16.91%',
 '  6.46%',
 '  6.46%',
 ' 11.80%',
 ' 11.80%',
 '  8.19%',
 '  6.46%',
 ' 26.31%',
 ' 16.91%',
 ' 10.72%',
 '  6.46%',
 '  6.46%',
 '  8.81%',
 ' 16.91%',
 ' 27.27%',
 '  8.19%',
 ' 10.72%',
 '  8.81%',
 ' 22.35%',
 ' 11.80%',
 ' 16.91%',
 ' 11.80%',
 ' 13.56%',
 ' 10.33%',
 ' 20.89%',
 ' 13.56%',
 ' 13.56%',
 '  8.19%',
 '  7.02%',
 ' 12.98%',
 '  6.46%',
 '  8.19%',
 ' 14.47%',
 ' 16.14%',
 ' 10.33%',
 ' 14.47%',
 ' 16.91%',
 '  8.19%',
 '  6.46%',
 '  7.02%',
 ' 10.72%',
 ' 16.91%',
 ' 15.02%',
 ' 12.98%',
 ' 13.56%',
 '  8.19%',
 '  7.02%',
 ' 11.31%',
 ' 20.89%',
 ' 11.80%',
 ' 10.33%',
 '  8.19%',
 ' 12.98%',
 ' 10.72%',
 ' 23.40%',
 ' 16.14%',
 '  7.02%',
 ' 24.37%',
 '  6.46%',
 ' 12.98%',
 '  6.46%',
 ' 10.33%',
 '  7.02%',
 ' 10.72%',
 ' 11.80%',
 ' 10.72%',
 '  6.46%',
 '  7.02%',
 '  6.46%',
 ' 10.72%',
 ' 13.56%',
 ' 10.33%',
 ' 14.47%',
 ' 16.14%',
 ' 22.35%',
 ' 14.47%',
 '  7.56%',
 ' 11.80%',
 ' 14.47%',
 ' 14.47%',
 '  8.19%',
 '  7.02%',
 ' 10.72%',
 '  7.02%',
 '  8.19%',
 '  8.19%',
 ' 15.02%',
 ' 27.27%',
 ' 11.80%',
 '  8.19%',
 '  6.46%',
 ' 12.98%',
 ' 11.80%',
 ' 17.97%',
 ' 18.94%',
 ' 11.31%',
 ' 13.56%',
 ' 17.97%',
 ' 10.72%',
 ' 15.02%',
 ' 14.47%',
 ' 18.94%',
 ' 16.14%',
 ' 11.80%',
 '  7.56%',
 ' 19.92%',
 ' 11.80%',
 ' 12.98%',
 '  7.56%',
 ' 11.80%',
 ' 13.56%',
 '  7.02%',
 ' 11.80%',
 '  7.02%',
 ' 12.98%',
 ' 12.98%',
 ' 10.72%',
 '  8.81%',
 ' 19.92%',
 '  7.56%',
 '  8.81%',
 ' 12.98%',
 ' 16.14%',
 '  6.46%',
 ' 13.56%',
 ' 15.02%',
 '  7.56%',
 ' 10.72%',
 ' 12.98%',
 ' 10.72%',
 '  7.56%',
 '  8.19%',
 ' 11.80%',
 '  7.56%',
 '  8.81%',
 ' 17.97%',
 ' 12.98%',
 '  8.81%',
 '  7.02%',
 '  8.19%',
 ' 13.56%',
 '  8.81%',
 ' 12.98%',
 ' 14.47%',
 ' 13.56%',
 '  8.19%',
 ' 11.80%',
 ' 13.56%',
 ' 16.91%',
 ' 12.98%',
 ' 11.80%',
 ' 11.31%',
 ' 10.33%',
 '  8.81%',
 ' 10.72%',
 ' 11.80%',
 ' 11.80%',
 '  8.19%',
 '  8.19%',
 ' 11.80%',
 ' 11.80%',
 ' 10.72%',
 '  7.02%',
 ' 11.80%',
 '  8.19%',
 '  7.56%',
 '  6.46%',
 ' 23.40%',
 ' 16.14%',
 '  8.19%',
 ' 17.97%',
 '  7.02%',
 '  7.02%',
 ' 11.80%',
 ' 11.31%',
 '  6.46%',
 ' 26.31%',
 ' 11.31%',
 '  8.81%',
 ' 15.02%',
 ' 13.56%',
 ' 11.31%',
 '  8.81%',
 '  8.81%',
 ' 14.47%',
 '  8.19%',
 '  7.56%',
 ' 10.33%',
 '  8.19%',
 ' 16.14%',
 ' 20.89%',
 '  8.19%',
 ' 16.91%',
 ' 10.33%',
 ' 16.91%',
 '  7.02%',
 ' 19.92%',
 '  8.19%',
 ' 11.80%',
 '  8.19%',
 ' 16.91%',
 ' 11.80%',
 ' 22.35%',
 ' 16.91%',
 '  8.81%',
 '  8.19%',
 '  8.81%',
 ' 16.14%',
 ' 15.02%',
 ' 16.14%',
 ' 16.91%',
 ' 16.91%',
 ' 11.80%',
 ' 10.33%',
 ' 10.72%',
 ' 11.80%',
 ' 15.02%',
 ' 15.02%',
 ' 10.72%',
 ' 16.14%',
 '  7.02%',
 ' 16.14%',
 ...]

In [0]:
df_new['int_rate'] = pd.Series([remove_percent_to_float(item) for item in list(df['int_rate'])])

In [34]:
df_new.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,10000,10000,10000.0,36 months,10.33,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8289.30,8289.30,2261.00,2261.00,1710.70,550.30,0.0,0.0,0.0,Jul-2019,324.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,4000,4000,4000.0,36 months,23.40,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3423.38,3423.38,1081.96,1081.96,576.62,505.34,0.0,0.0,0.0,Jul-2019,155.68,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (31-120 days),n,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.96,895.96,543.83,352.13,0.0,0.0,0.0,Jun-2019,180.69,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,23000,23000,23000.0,60 months,20.89,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21353.16,21353.16,4307.45,4307.45,1646.84,2660.61,0.0,0.0,0.0,Jul-2019,620.81,Sep-2019,Aug-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,8000,8000,8000.0,36 months,23.40,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,6846.83,6846.83,2163.85,2163.85,1153.17,1010.68,0.0,0.0,0.0,Jul-2019,311.35,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
# value_counts gives the value for each title
# by default drops na 

#df['emp_title'].value_counts()

#df['emp_title'].value_counts(dropna=False)

# top 20 use .head(20)

df_new['emp_title'].value_counts(dropna=False).head(20)

NaN                   20947
Teacher                2090
Manager                1773
Registered Nurse        952
Driver                  924
RN                      726
Supervisor              697
Sales                   580
Project Manager         526
General Manager         523
Office Manager          521
Owner                   420
Director                402
Operations Manager      387
Truck Driver            387
Nurse                   326
Engineer                325
Sales Manager           304
manager                 301
Supervisor              270
Name: emp_title, dtype: int64

In [36]:
df_new.describe(exclude='number')

,term,grade,sub_grade,emp_title,emp_length,home_ownership,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,earliest_cr_line,revol_util,initial_list_status,last_pymnt_d,next_pymnt_d,last_credit_pull_d,application_type,verification_status_joint,sec_app_earliest_cr_line,hardship_flag,hardship_type,hardship_reason,hardship_status,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_loan_status,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date
count,128412,128412,128412,107465,116708,128412,128412,128412,128412,128412,128412,128412,128412,128412,128412,128256,128412,128253,112289,128411,128412,14848,16782,128412,27,27,27,27,27,27,27,128412,111,111,111
unique,2,7,35,43892,11,4,3,3,7,2,12,12,880,50,644,1074,2,12,3,12,2,3,573,2,1,6,3,3,4,3,4,2,6,3,7
top,36 months,A,A4,Teacher,10+ years,MORTGAGE,Not Verified,Oct-2018,Current,n,debt_consolidation,Debt consolidation,112xx,CA,Aug-2006,0%,w,Aug-2019,Sep-2019,Aug-2019,Individual,Not Verified,Aug-2006,N,INTEREST ONLY-3 MONTHS DEFERRAL,EXCESSIVE_OBLIGATIONS,ACTIVE,Aug-2019,Oct-2019,Aug-2019,In Grace Period,N,Aug-2019,ACTIVE,Jul-2019
freq,88179,38011,9770,2090,38826,63490,58350,46305,108584,128398,70603,70603,1370,17879,1130,1132,114498,105424,112228,117910,111630,6360,155,128387,27,8,25,19,14,15,10,128301,48,99,43

In [39]:

#df_new['emp_title'].value_counts(dropna=False)

# convert to a two col dstaframe with new index 
# use reset_index()
#df_new['emp_title'].value_counts(dropna=False).reset_index()

# To get the number of unique employment titles, use shape[0]
df_new['emp_title'].value_counts(dropna=False).reset_index().shape[0]

43893

In [41]:
df_new['emp_title'].isnull().sum()

20947

# STRETCH OPTIONS

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01